/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveQueryRouteImport } from './routes/live-query'
import { Route as LiveSuspenseQueryRouteImport } from './routes/live-suspense-query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveQueryRoute = LiveQueryRouteImport.update({
  id: '/live-query',
  path: '/live-query',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSuspenseQueryRoute = LiveSuspenseQueryRouteImport.update({
  id: '/live-suspense-query',
  path: '/live-suspense-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-query': typeof LiveQueryRoute
  '/live-suspense-query': typeof LiveSuspenseQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-query': typeof LiveQueryRoute
  '/live-suspense-query': typeof LiveSuspenseQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-query': typeof LiveQueryRoute
  '/live-suspense-query': typeof LiveSuspenseQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live-query' | '/live-suspense-query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live-query' | '/live-suspense-query'
  id: '__root__' | '/' | '/live-query' | '/live-suspense-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveQueryRoute: typeof LiveQueryRoute
  LiveSuspenseQueryRoute: typeof LiveSuspenseQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-query': {
      id: '/live-query'
      path: '/live-query'
      fullPath: '/live-query'
      preLoaderRoute: typeof LiveQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-suspense-query': {
      id: '/live-suspense-query'
      path: '/live-suspense-query'
      fullPath: '/live-suspense-query'
      preLoaderRoute: typeof LiveSuspenseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveQueryRoute: LiveQueryRoute,
  LiveSuspenseQueryRoute: LiveSuspenseQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
